### ISSUE TITLE
new update messed it up

### ISSUE THREAD

**Issue by sefried12** [ThornyFFXI/PacketFlow#1]
i may just be dumb but new update keeps crashing whenever i open i inventory

**Comment by ThornyFFXI** [comment]
You'd need to be more specific.  If you crash *every* time you open inventory, no matter what, it's probably not packetflow.  If you outline exact circumstances to cause a crash, I can attempt to reproduce, but packetflow does not directly alter the contents of packets, so it is unlikely to be related in my opinion.

**Comment by sefried12** [comment]
Let me apologize it wasnt this at all my mog 5-8 isnt showing up even though i paid for it so it was that issue i'm sorry ><
